doc_vote/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.core.urlresolvers import reverse_lazy
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^$', RedirectView.as_view(url=reverse_lazy("polls:index"))),
    url(r'^admin/', admin.site.urls),
    url(r'^polls/', include("polls.urls", namespace="polls")),
    url(r'^user/', include("user.urls", namespace="user")),
]

polls/urls.py
from django.conf.urls import url
from .views import index, detail, vote, result, results, create

urlpatterns = [
    # /polls
    url(r'^$', index, name="index"),

    # /polls/results
    url(r'^results$', results, name="results"),

    # /polls/create
    url(r'^create$', create, name="create"),

    # /polls/poll_id
    url(r'^(?P<poll_id>[0-9]+)$', detail, name="detail"),

    # /polls/poll_id
    url(r'^(?P<poll_id>[0-9]+)/vote$', vote, name="vote"),

    # /polls/poll_id/result
    url(r'^(?P<poll_id>[0-9]+)/result$', result, name="result"),

]

user/urls.py
from django.conf.urls import url
from .views import user_login, user_registration, user_logout

urlpatterns = [
    url(r'^login$', user_login, name="user_login"),
    url(r'^signup', user_registration, name="user_signup"),
    url(r'^logout$', user_logout, name="user_logout"),
]

polls/models.py
import datetime
from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField(auto_now_add=True, auto_now=False)

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    @property
    def sort_choice_votes(self):
        return self.choice_set.order_by('-votes')


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=100)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.question.question_text} | {self.choice_text}"

polls/forms.py
from django import forms
from .models import Question, Choice
from django.forms.formsets import BaseFormSet


class QuestionModelForm(forms.ModelForm):
    question_text = forms.CharField(widget=forms.Textarea)

    class Meta:
        model = Question
        fields = ['question_text']


class ChoiceModelForm(forms.ModelForm):
    class Meta:
        model = Choice
        fields = ['choice_text']


class ChoiceFormSet(BaseFormSet):
    def __init__(self, *args, **kwargs):
        super(ChoiceFormSet, self).__init__(*args, **kwargs)
        for form in self.forms:
            form.empty_permitted = False

polls/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.forms.formsets import formset_factory
from django.http import Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Q

from polls.models import Question, Choice
from .forms import QuestionModelForm, ChoiceModelForm, ChoiceFormSet


def index(request):
    polls = Question.objects.all().order_by('-id')
    query = request.GET.get('s')
    if query:
        polls = polls.filter(
            Q(question_text__icontains=query) |
            Q(choice__choice_text__contains=query)
        )

    paginator = Paginator(polls, 5)
    page = request.GET.get('page')

    try:
        polls = paginator.page(page)
    except PageNotAnInteger:
        polls = paginator.page(1)
    except EmptyPage:
        polls = paginator.page(paginator.num_pages)

    return render(request, "polls/index.html", {"polls": polls})


def results(request):
    polls = Question.objects.all()
    paginator = Paginator(polls, 8)
    page = request.GET.get('page')
    try:
        polls = paginator.page(page)
    except PageNotAnInteger:
        polls = paginator.page(1)
    except EmptyPage:
        polls = paginator.page(paginator.num_pages)
    return render(request, "polls/results.html", {"polls": polls})


@login_required(login_url="/user/login")
def detail(request, poll_id):
    try:
        poll = Question.objects.get(pk=poll_id)
    except Question.DoesNotExist:
        raise Http404("Sorry Poll Doesn't Found")

    return render(request, "polls/detail.html", {"poll": poll})


def vote(request, poll_id):
    poll = get_object_or_404(Question, pk=poll_id)
    if request.method == "POST":
        try:
            selected_choice = poll.choice_set.get(id=request.POST['vote'])
        except (KeyError, Choice.DoesNotExist):
            messages.add_message(request, messages.ERROR, "Please select a choice")
            return redirect("polls:detail", poll_id=poll.id)

        selected_choice.votes += 1
        selected_choice.save()
        messages.success(request, "Your vote submitted, Thanks for vote <3")

    return redirect("polls:detail", poll_id=poll.id)


def result(request, poll_id):
    poll = get_object_or_404(Question, pk=poll_id)
    return render(request, "polls/result.html", {"poll": poll})


@login_required(login_url='/user/login')
def create(request):
    if not request.user.is_superuser:
        messages.success(request, "You don't have permission for create new question")
        return redirect("polls:index")

    ChoiceForm = formset_factory(ChoiceModelForm, max_num=10, formset=ChoiceFormSet)
    QuestionForm = QuestionModelForm(None)
    if request.method == "POST":
        QuestionForm = QuestionModelForm(request.POST)
        ChoiceForm = ChoiceForm(request.POST)
        if ChoiceForm.is_valid() and QuestionForm.is_valid():
            question = QuestionForm.save()
            for form in ChoiceForm.forms:
                question.choice_set.create(choice_text=form.cleaned_data['choice_text'])
            messages.success(request, "Successfully Created Question")
            return redirect("polls:detail", poll_id=question.id)
        else:
            messages.error(request, "Form Doesn't Valid")
            return render(request, "polls/create.html", {"question_form": QuestionForm, "choice_forms": ChoiceForm})

    return render(request, "polls/create.html", {
        "question_form": QuestionForm,
        "choice_forms": ChoiceForm
    })

polls/templates/polls/create.html
{% extends "polls/layout.html" %}

{% block title %} {{ block.super }} | Create new poll {% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h2 class="text-center">Create New Question</h2>
                        <form action="{% url "polls:create" %}" method="post">
                            {% csrf_token %}
                            {% include "polls/error_message.html" %}
                            {% include "polls/form_template.html" with form=question_form %}
                            {{ choice_forms.management_form }}
                            <div class="row">
                                {% for form in choice_forms %}
                                    {% include "polls/formset_template.html" with form=form %}
                                {% endfor %}
                            </div>
                            <div class="form-group">
                                <input type="submit" value="Create" class="btn btn-primary">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

polls/templates/polls/detail.html
{% extends "polls/layout.html" %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h1>{{ poll.question_text }}</h1>
                        <form action="{% url "polls:vote" poll.id %}" method="post">
                            {% csrf_token %}
                            {% for choice in poll.choice_set.all %}
                                <div class="radio">
                                    <label>
                                        <input type="radio" name="vote" id="choice-{{ forloop.counter }}" value="{{ choice.id }}"> {{ choice.choice_text }}
                                    </label>
                                </div>
                            {% endfor %}
                            <div class="form-group">
                                <input type="submit" value="submit" class="btn btn-success">
                                <a href="{% url "polls:result" poll.id %}" class="btn btn-link">Result</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

polls/templates/polls/error_message.html
{% if error_message %}
    <div class="alert-message alert alert-danger">
        {{ error_message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
{% endif %}

polls/templates/polls/flash_message.html
{% if messages %}
    {% for message in messages %}
        <script>
            swal({
                title: '{{ message }}',
                type: '{{ message.tags }}',
                timer: 1500
            });
        </script>
    {% endfor %}
{% endif %}

polls/templates/polls/form_template.html
{% load formfilters %}
{% for field in form %}
    <div class="form-group {% if field.errors %} has-error {% endif %}">
        <label for="{{ field.auto_id }}" class="control-label">{{ field.label }}</label>

        {{ field|inputField }}

        {% if field.errors %}
            <p class="help-block">{{ field.errors.as_text }}</p>
        {% endif %}
    </div>
{% endfor %}

polls/templates/polls/formset_template.html
{% load formfilters %}
{% for field in form %}
    <div class="item">
        <div class="col-md-9 {% if field.errors %} has-error {% endif %} input-right">
            <label for="{{ field.auto_id }}" class="control-label">{{ field.label }}</label>

            {{ field|inputField }}

            {% if field.errors %}
                <p class="help-block">{{ field.errors.as_text }}</p>
            {% endif %}
        </div>
        <div class="col-md-3 text-center btn-add-more btn-left">
            <button class="btn btn-sm btn-success add-more"><i class="glyphicon glyphicon-plus"></i></button>
            <button class="btn btn-sm btn-warning delete-this"><i class="glyphicon glyphicon-remove"></i></button>
        </div>
    </div>
{% endfor %}

polls/templates/polls/index.html
{% extends "polls/layout.html" %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <ul class="list-group">
                    {% if polls %}
                        {% for poll in polls %}
                            <li class="list-group-item">
                                {% if user.is_authenticated %}
                                    <a href="{% url "polls:detail" poll.id %}">{{ poll.question_text }}</a> -
                                    <a href="{% url "polls:result" poll.id %}" class="label label-success">Result</a>
                                {% else %}
                                    <a href="{% url "polls:result" poll.id %}">{{ poll.question_text }}</a>
                                {% endif %}
                            </li>
                        {% endfor %}
                    {% else %}
                        <li class="list-group-item list-group-item-danger">No Polls Created Yet!</li>
                    {% endif %}
                </ul>
                {% include "polls/pagination.html" with pages=polls %}
            </div>
        </div>
    </div>
{% endblock %}

polls/templates/polls/layout.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}TMPolls{% endblock %}</title>
    <link rel="stylesheet" href="{% static "polls/css/bootstrap.css" %}">
    <link rel="stylesheet" href="{% static "polls/css/sweetalert2.min.css" %}">
    <link rel="stylesheet" href="{% static "polls/css/style.css" %}">
    <script src="{% static "polls/js/sweetalert2.min.js" %}"></script>
</head>
<body>
    {% include "polls/navigation.html" %}
    {% include "polls/flash_message.html" %}
    {% block content %} {% endblock %}
    <script src="{% static "polls/js/jquery.js" %}"></script>
    <script src="{% static "polls/js/bootstrap.min.js" %}"></script>
    <script src="{% static "polls/js/main.js" %}"></script>
</body>
</html>

polls/templates/polls/navigation.html
<nav class="navbar navbar-inverse" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{% url "polls:index" %}">TMPolls</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav">
            {% if user.is_superuser %}
                <li><a href="{% url "polls:create" %}">Create Question</a></li>
            {% endif %}
            <li><a href="{% url "polls:results" %}">Results</a></li>
        </ul>
        <form class="navbar-form navbar-left" role="search" action="{% url "polls:index" %}" method="get">
            <div class="form-group">
                <input type="text" class="form-control" placeholder="Search" name="s" value="{{ request.GET.s }}">
            </div>
            <button type="submit" class="btn btn-default">Submit</button>
        </form>

        <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Hello, {{ user.username }}
                        <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url "user:user_logout" %}">Logout</a></li>
                    </ul>
                </li>
            {% else %}
                <li><a href="{% url "user:user_login" %}">Login</a></li>
                <li><a href="{% url "user:user_signup" %}">Signup</a></li>
            {% endif %}

        </ul>
    </div><!-- /.navbar-collapse -->
</nav>

polls/templates/polls/pagination.html
{% if pages.has_other_pages %}
    <ul class="pagination">
        {% if pages.has_previous %}
            <li>
                <a href="?page={{ pages.previous_page_number }}{% if request.GET.s %}&s={{ request.GET.s }}{% endif %}">&laquo;</a>
            </li>
        {% else %}
            <li class="disabled"><a href="#">&laquo;</a></li>
        {% endif %}

        {% for page in pages.paginator.page_range %}
            {% if pages.number == page %}
                <li class="active"><a href="?page={{ page }}">{{ page }}</a></li>
            {% else %}
                <li>
                    <a href="?page={{ page }}{% if request.GET.s %}&s={{ request.GET.s }}{% endif %}">{{ page }}</a>
                </li>
            {% endif %}
        {% endfor %}

        {% if pages.has_next %}
            <li>
                <a href="?page={{ pages.next_page_number }}{% if request.GET.s %}&s={{ request.GET.s }}{% endif %}">&raquo;</a>
            </li>
        {% else %}
            <li class="disabled"><a href="#">&raquo;</a></li>
        {% endif %}
    </ul>
{% endif %}

polls/templates/polls/result.html
{% extends "polls/layout.html" %}

{% block title %} {{ block.super }} | {{ poll.question_text }} {% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h2 class="text-center"><strong>Result Of:</strong> {{ poll.question_text }}</h2>
                        <ul class="list-group">
                            {% for choice in poll.sort_choice_votes %}
                                <li class="list-group-item">
                                    {{ choice.choice_text }}
                                    <span class="label label-success">{{ choice.votes }}</span>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

polls/templates/polls/results.html
{% extends "polls/layout.html" %}

{% block title %}
    {{ block.super }} | Results
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                {% if polls %}
                    {% for poll in polls %}
                        <div class="panel panel-default">
                            <h2 class="text-center">{{ poll.question_text }}</h2>
                            <ul class="list-group">
                                {% for choice in poll.sort_choice_votes %}
                                    <li class="list-group-item">
                                        {{ choice.choice_text }}
                                        <span class="label label-success">{{ choice.votes }}</span>
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                    {% endfor %}
                {% else %}
                    <div class="panel panel-danger">
                        <div class="panel-body">
                            <h1 class="text-center">No Polls Created Yet!</h1>
                        </div>
                    </div>
                {% endif %}
                {% include "polls/pagination.html" with pages=polls %}
            </div>
        </div>
    </div>
{% endblock %}